label q3_2_2:
    qian_speaking "我还是觉得……应该把知道的事情都说出来。\n虽然，不知道结果会变得怎样……"
    ying_speaking "嗯。"
    qian_speaking "……走吧。"
    qian "我抓起她的手，心脏在高速跳动。"
    "砰！"
    qian "堆积成山的垃圾被人粗暴地扫开，一层又一层。"
    ying_speaking "小心……"
    qian "我设置好终端机的屏幕，让它能够以最大的尺寸投影出画面。"
    qian "而后，我压抑住恐惧与不安，直直地冲向充满人群的外侧——"
    qian_speaking "我们就在这！但是请你们先看完这些！"
    unknown "住嘴！"
    "砰！"
    qian_speaking "呜……！请你们——看——！"
    qian "明亮的投影在头顶上展开，照亮我失去血色的表情。"
    qian "这是……我自己选择的道路。"
    "ENDING"
